### PR TITLE
Fix prettylog piping

### LINKED ISSUE #628: prettylog only displays the first line of the output
I have a service that uses zerolog and outputs logs in json.
When I try to pipe its output to prettylog, it's only displaying its first line and then silently exits:

```
$ journalctl -u cosmovisor -f --output=cat -n 100 | prettylog
2:03AM INF Replay: Vote blockID={"hash":"","parts":{"hash":"","total":0}} height=18396932 module=consensus peer=72829b78b38408b03793ed389b9f16596b82c306 round=0 type=1
$
```

This makes it kinda useless for piping.

Adding a `for { }` or `select { }` after this line https://github.com/rs/zerolog/blob/master/cmd/prettylog/prettylog.go#L22 would likely fix that, as it seems like it creates a Writer and just exits. (I tested the `for {}` approach and it seems to work, but not sure if it's the optimal solution). This way it outputs data unless the process is killed by Ctrl+C:

```
$ journalctl -u cosmovisor -f --output=cat -n 100 | go run prettylog.go
2:04AM INF Ensure peers module=pex numDialing=1 numInPeers=0 numOutPeers=2 numToDial=7
2:04AM INF Timed out dur=4767.27112 height=18396945 module=consensus round=0 step=1
2:04AM INF finalizing commit of block hash={} height=18396945 module=consensus num_txs=4 root=65DB37F7DA3CC476BFDFBB34018E8B68CC9C15028509013C14038CE479100A4C
2:04AM INF Error reconnecting to peer. Trying again addr={"id":"538ebe0086f0f5e9ca922dae0462cc87e22f0a50","ip":"34.122.34.67","port":26656} err="dial tcp 34.122.34.67:26656: i/o timeout" module=p2p tries=10
2:04AM INF Error reconnecting to peer. Trying again addr={"id":"585794737e6b318957088e645e17c0669f3b11fc","ip":"54.160.123.34","port":26656} err="dial tcp 54.160.123.34:26656: i/o timeout" module=p2p tries=9
2:04AM INF Error reconnecting to peer. Trying again addr={"id":"5b4ed476e01c49b23851258d867cc0cfc0c10e58","ip":"206.189.4.227","port":26656} err="dial tcp 206.189.4.227:26656: i/o timeout" module=p2p tries=10
^Csignal: interrupt

$
```

### PR DESCRIPTION
**Pull request by freak12techno**
Fixes #628.

Basically, instead of directly piping the output from pipe, it now reads it via bufio.Scanner, which splits events by newline, so if the input is buffered, it groups logs by splitting events by newline, and in case it fails, it would just output the logs directly.

Example on testing it:
1) broken output (e.g. the whole string is invalid JSON as it's essentially split into two chunks by a newline) - displays the input as it is:
```
➜  prettylog git:(fix-prettylog-piping) ✗ cat test.sh
while true; do
echo '{"level":"info","module":"txindex","height":18397037,"tim';
sleep 0.5;
echo 'e":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}'
sleep 0.5
done

➜  prettylog git:(fix-prettylog-piping) ✗ bash test.sh | ./prettylog
{"level":"info","module":"txindex","height":18397037,"tim
e":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"tim
e":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
```

2) chunked output - displays output as pretty logs
```
➜  prettylog git:(fix-prettylog-piping) ✗
➜  prettylog git:(fix-prettylog-piping) ✗ cat test.sh
while true; do
echo -n '{"level":"info","module":"txindex","height":18397037,"tim';
sleep 0.5;
echo 'e":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}'
sleep 0.5
done

➜  prettylog git:(fix-prettylog-piping) ✗ bash test.sh | ./prettylog
2:13AM INF indexed block exents height=18397037 module=txindex
2:13AM INF indexed block exents height=18397037 module=txindex
2:13AM INF indexed block exents height=18397037 module=txindex
2:13AM INF indexed block exents height=18397037 module=txindex
2:13AM INF indexed block exents height=18397037 module=txindex
```

3) ideal output (nothing is buffered, whatever is piping data into prettylog splits it by the newline) - displays output as pretty logs
```
➜  prettylog git:(fix-prettylog-piping) ✗ cat test.sh
while true; do
echo '{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}'
sleep 0.5
done
➜  prettylog git:(fix-prettylog-piping) ✗ bash test.sh | ./prettylog
2:13AM INF indexed block exents height=18397037 module=txindex
2:13AM INF indexed block exents height=18397037 module=txindex
2:13AM INF indexed block exents height=18397037 module=txindex
2:13AM INF indexed block exents height=18397037 module=txindex
```

### CODE REVIEW

File: cmd/prettylog/prettylog.go [hunk 1]
```diff
@@ -19,7 +19,18 @@ func main() {
...
+			bytesToWrite := scanner.Bytes()
+			_, err := writer.Write(bytesToWrite)
+			if err != nil {
+				if errors.Is(err, io.EOF) {
+					break
+				}
+
+				fmt.Printf("%s\n", bytesToWrite)
+			}
+		}
```
Comment (rs) [inline cmd/prettylog/prettylog.go:33]: Could you please make this a function and reuse it for the code below (for file arg)?

**Review by rs — CHANGES_REQUESTED** [review]

File: cmd/prettylog/prettylog.go (hunk 1 above)
Comment (freak12techno) [reply cmd/prettylog/prettylog.go:33]: Yeah, I thought about this, but it's slightly different in terms of how the errors are treated. What do you think would be the best way to do in both cases if error occurs, crash the app and display the error message, or display the output as is?

Comment (rs) [reply cmd/prettylog/prettylog.go:33]: Showing the line as-is is probably sensible for such a tool.

**Comment by freak12techno** [comment]
@rs fixed your comments above, here's how it works now:

```
➜  prettylog git:(fix-prettylog-piping) ✗ cat test.sh
echo "First case: invalid JSON"
for i in {1..5}; do
echo '{"level":"info","module":"txindex","height":18397037,"ti'
echo 'me":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}'
sleep 0.5
done

echo "Second case: chunked valid JSON"
for i in {1..5}; do
echo -n '{"level":"info","module":"txindex","height":18397037,"ti'
echo 'me":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}'
sleep 0.5
done

echo "Third case: not chunked valid JSON"
for i in {1..5}; do
echo '{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}'
sleep 0.5
done

➜  prettylog git:(fix-prettylog-piping) ✗ bash test.sh | ./prettylog
First case: invalid JSON
{"level":"info","module":"txindex","height":18397037,"ti
me":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"ti
me":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"ti
me":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"ti
me":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"ti
me":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
Second case: chunked valid JSON
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Third case: not chunked valid JSON
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex

➜  prettylog git:(fix-prettylog-piping) ✗ cat test2.txt
{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":1839
7037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00",
"message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}

➜  prettylog git:(fix-prettylog-piping) ✗ ./prettylog test2.txt test2.txt
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
{"level":"info","module":"txindex","height":1839
7037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00",
"message":"indexed block exents"}
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
{"level":"info","module":"txindex","height":1839
7037,"time":"2023-12-23T02:13:47+03:00","message":"indexed block exents"}
{"level":"info","module":"txindex","height":18397037,"time":"2023-12-23T02:13:47+03:00",
"message":"indexed block exents"}
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex
Sat, 23 Dec 2023 02:13:47 MSK INF indexed block exents height=18397037 module=txindex

➜  prettylog git:(fix-prettylog-piping) ✗ ./prettylog test3.txt test2.txt
test3.txt open: open test3.txt: no such file or directory%
```

My concerns here:
1) if there are multiple files and some of them could not be opened (e.g. due to permissions or file being missing or something else) the program will fail and other files won't be processed (like in the last example above), is that expected? This logic wasn't changed with this PR, just want to make sure it's expected (or not)

2) is there a point of supporting multiple files when it can be done via bash query, like this:
```
for filename in folder/*.json; do
prettylog $filename
done
```
?

3) is there a point of even supporting the file input when it also can be done via the bash query, like `cat filename.json | prettylog`?

(IMO it makes the tool extra complex without the reason, but there may be reasoning I am not aware of, wonder what's your opinion on all of that)

**Review by rs — APPROVED** [review]
