### PR TITLE
ctx: Modify WithContext to use a non-pointer receiver

### LINKED ISSUE #116: Chaining WithContext call is broken
#81 broke clients that chain `WithContext` calls. According to the docs, I expect the following program to compile (lifted from #80):

```
package main

import (
	"context"
	"github.com/rs/zerolog"
	"os"
)

func process(ctx context.Context, id int) {
	log := zerolog.Ctx(ctx).With().Int("id", id).Logger()
	child(log.WithContext(ctx))
}

func child(ctx context.Context) {
	zerolog.Ctx(ctx).Info().Msg("hello from child")
}

func main() {
	ctx := zerolog.New(os.Stdout).WithContext(context.Background())
	zerolog.Ctx(ctx).Info().Msg("processing 1")
	process(ctx, 1)

	zerolog.Ctx(ctx).Info().Msg("processing 2")
	process(ctx, 2)

	zerolog.Ctx(ctx).Info().Msg("done")
}
```

but it fails: 
```
# command-line-arguments
cmd/main.go:19:31: cannot call pointer method on zerolog.New(os.Stdout)
cmd/main.go:19:31: cannot take the address of zerolog.New(os.Stdout)
```

Reason being that variables in go are addressable but return values from functions are not.

The current workaround is this: 
```
package main

import (
	"context"
	"github.com/rs/zerolog"
	"os"
)

func process(ctx context.Context, id int) {
	log := zerolog.Ctx(ctx).With().Int("id", id).Logger()
	child(log.WithContext(ctx))
}

func child(ctx context.Context) {
	zerolog.Ctx(ctx).Info().Msg("hello from child")
}

func main() {
	l := zerolog.New(os.Stdout)
	ctx := l.WithContext(context.Background())
	zerolog.Ctx(ctx).Info().Msg("processing 1")
	process(ctx, 1)

	zerolog.Ctx(ctx).Info().Msg("processing 2")
	process(ctx, 2)

	zerolog.Ctx(ctx).Info().Msg("done")
}
```

Output:
```
{"level":"info","message":"processing 1"}
{"level":"info","id":1,"message":"hello from child"}
{"level":"info","message":"processing 2"}
{"level":"info","id":2,"message":"hello from child"}
{"level":"info","message":"done"}
```

### PR DESCRIPTION
**Pull request by nickcorin**
This PR addresses the issues discussed in #116 and #400.

I have modified the receiver for `WithContext` to use a non-pointer receiver and fixed the tests.

The alternative to this, as discussed, would be to modify `Logger()` to return a pointer. If this is the preferred fix, I'd be happy to implement. However, it will have more knock-on effects.

Fixes #116.

### CODE REVIEW

**Comment by pschwartz** [comment]
Watching to see status as I am making use of this and breaking down into multiple statements including a .UpdateContext() is not as clean as the single line.

File: ctx.go [hunk 1]
```diff
@@ -25,17 +25,17 @@ type ctxKey struct{}
 //     l.UpdateContext(func(c Context) Context {
 //         return c.Str("bar", "baz")
 //     })
-func (l *Logger) WithContext(ctx context.Context) context.Context {
+func (l Logger) WithContext(ctx context.Context) context.Context {
 	if lp, ok := ctx.Value(ctxKey{}).(*Logger); ok {
-		if lp == l {
+		if lp == &l {
```
Comment (mitar) [inline ctx.go:30]: So this change makes no sense. Value receiver methods get a new copy of `l` every time they are called. So here you are taking an address of this temporary copied value and comparing it with context pointer. This will always be false. This has been fixed by removing this check in #499.
